name: benchmarks
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write
  repository-projects: write
    
env:
  PYTHON_VERSION: 3.9.13

jobs:
  benchmark:
    runs-on: [linux]
    timeout-minutes: 15
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Checkout elocare
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install pytest pytest-benchmark
    - name: Run benchmarks
      run: |
        pytest -m benchmark --benchmark-json=benchmarks/output.json
    - name: Store benchmark results (if pushed to master)
      uses: benchmark-action/github-action-benchmark@v1.14.0
      with:
        tool: 'pytest'
        output-file-path: benchmarks/output.json
        github-token: ${{ secrets.GITHUB_TOKEN  }}
        alert-threshold: '200%'
        comment-on-alert: true
        comment-always: true
        auto-push: ${{ github.event_name != 'pull_request' }}
        fail-on-alert: true
        gh-pages-branch: benchmarks
        benchmark-data-dir-path: docs
