name: scan_container

on:
  schedule:
  # Run 02:00 every monday (same as dependabot)
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  scan_db:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2.0.0
      with:
        sarif_file: snyk.sarif